JuiceTelegramBotWebApp/ViewModels/JuiceVM.cs
using JuiceTelegramBot.Core.DomainObject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JuiceTelegramBotWebApp.ViewModels
{
    public class JuiceVM:Juice
    {
        public bool IsChecked { get; set; }

        public JuiceVM()
        {
        }

        public JuiceVM(Juice juice)
        {
            this.Approved = juice.Approved;
            this.IsCustom = juice.IsCustom;
            this.JuiceDateTime = juice.JuiceDateTime;
            this.Name = juice.Name;
            this.UserName = juice.UserName;
        }
    }
}

JuiceTelegramBotWebApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JuiceTelegramBotWebApp.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

JuiceTelegramBotWebApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JuiceTelegramBotWebApp.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

JuiceTelegramBotWebApp/Pages/CreateBeverage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JuiceTelegramBot.Core.Model;
using JuiceTelegramBot.Core.Services;
using JuiceTelegramBotWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace JuiceTelegramBotWebApp.Pages
{
    public class CreateModel : PageModel
    {
        private ILogger<CreateModel> Log;
        private readonly IJuiceService juiceService;
        public CreateModel( ILogger<CreateModel> logger, IJuiceService juiceService)
        {
            Log = logger;
            this.juiceService = juiceService ?? throw new ArgumentNullException(nameof(juiceService));
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public JuiceVM Juice { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            if (juiceService.IsInJuices(Juice.Name))
            {
                Message = $"Bevarage {Juice.Name} already exist!";
                return Page();
            }
            juiceService.AddJuice(Juice.Name, false, true, DateTime.Now, "Admin");
            juiceService.IsInJuices(Juice.Name);
            return RedirectToPage("/Index");
        }
    }
}

JuiceTelegramBotWebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JuiceTelegramBotWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

JuiceTelegramBotWebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JuiceTelegramBot.Core.Model;
using JuiceTelegramBot.Core.Services;
using JuiceTelegramBotWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace JuiceTelegramBotWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private ILogger<CreateModel> Log;
        private readonly IJuiceService juiceService;
        public IndexModel(ILogger<CreateModel> logger, IJuiceService juiceService)
        {
            Log = logger ?? throw new ArgumentNullException(nameof(logger));
            this.juiceService = juiceService ?? throw new ArgumentNullException(nameof(juiceService));
        }

        [BindProperty]
        public IList<JuiceVM> Juices { get; set; }

        public IList<OrderDb> Orders { get; private set; }

        public void OnGetAsync()
        {
            Juices =  juiceService.GetJuiceList().Select(j => new JuiceVM(j)).ToList();
        }

        // async method is required by convention
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        public async Task<IActionResult> OnPostApprovedAsync()
        {
            Juices.AsParallel()
                .Where(juice => juice.IsChecked)
                .ForAll(juice => juiceService.ApproveJuice(juice.Name));
            
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(string name)
        {
            Juices
                .Where(juice => juice.IsChecked)
                .ToList()
                .ForEach(juice => juiceService.DeleteByName(juice.Name));

            return RedirectToPage();
        }
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
    }
}

JuiceTelegramBotWebApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JuiceTelegramBotWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

JuiceTelegramBotWebApp/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

JuiceTelegramBotWebApp/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JuiceTelegramBotWebApp/Pages/CreateBeverage.cshtml
@page
@model JuiceTelegramBotWebApp.Pages.CreateModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create new beverage</h2>
<form method="POST">
    <div asp-validation-summary="All"></div>
    <div>Enter beverage name:<input asp-for="Juice.Name" />@Model.Message</div>
    <input type="submit" />
</form>

JuiceTelegramBotWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Is custom</th>
                <th>Approved</th>
                <th>Added by</th>
                <th>Creation date</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Juices.Count; i++)
            {
                @Html.HiddenFor(m => m.Juices[i].Name)
                <tr>
                    <td>@Html.EditorFor(m => m.Juices[i].IsChecked)</td>
                    <td>@Html.DisplayFor(m => m.Juices[i].Name)</td>
                    <td>@Html.DisplayFor(m => m.Juices[i].IsCustom)</td>
                    <td>@Html.DisplayFor(m => m.Juices[i].Approved)</td>
                    <td>@Html.DisplayFor(m => m.Juices[i].UserName)</td>
                    <td>@Html.DisplayFor(m => m.Juices[i].JuiceDateTime)</td>
                </tr>
            }
            <tr>
                <td>
                    <button type="submit" asp-page-handler="approved">Approve selected</button>
                </td>
                <td>
                    <button type="submit" asp-page-handler="delete">Delete selected</button>
                </td>
            </tr>
            <tr><td><div><a asp-page="./Createbeverage">Create a new beverage</a></div></td></tr>
        </tbody>
    </table>
</form>

JuiceTelegramBotWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JuiceTelegramBotWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">JuiceTelegramBotWebApp</a>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - JuiceTelegramBotWebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>